### ISSUE TITLE
facade 

### ISSUE THREAD

**Issue by robertnicjoo** [xendit/xendit-php#114]
Is there any **Facade** or **Trait**, **Provider** in this package that we can introduce it into packages file `config/app.php` in Laravel?

**Comment by nazieb** [comment]
Hi @robertnicjoo, since this package is framework-agnostic, it does not provide integration for Laravel out of the box.

However to use it in Laravel projects, the easiest way is to call the `Xendit::setApiKey` inside the existing `AppServiceProvider.php` in the `app/Providers` directory.

```php
class AppServiceProvider extends ServiceProvider
{
    public function register() {
        \Xendit\Xendit::setApiKey(env('XENDIT_API_KEY'));
    }
}
```

After that, elsewhere in your project you can use the library right away. For example, in `routes/web.php`:
```php
Route::get('/balance', function () {
    $balance = \Xendit\Balance::getBalance('CASH');
    dd($balance);
});
```

**Comment by stanleynguyen** [comment]
Stale. Closing
