### ISSUE TITLE
What's MAX_DECIMAL_EXCEEDED_ERROR means?

### ISSUE THREAD

**Issue by vasilenka** [xendit/xendit-php#158]
Try searching the docs and API reference but can't find anything about this error response

I can guess from the message, but this one error caught us off-guard because there's nothing about it in the docs
And I'm a little bit worried if there's another edge cases that's not on the docs yet

**Comment by cindyharum29** [comment]
Hi @vasilenka 

Thank you for reaching us. We would like to inform you that MAX_DECIMAL_EXCEEDED_ERROR returned because we don't support decimal in IDR. We put a note on your suggestion to keep updated our api reference.

Thank you for the feedback and sorry for the inconvenience.

Regards,
Cindy Harum
