### ISSUE TITLE
Creating Payment Request Using 3.0.0 SDK

### ISSUE THREAD

**Issue by NaMLiM** [xendit/xendit-php#209]
Hello I tried creating Payment Request using the new sdk.

i am using the example code from the docs and the output is this.
```
Xendit\PaymentRequest\Error Object(
    [openAPINullablesSetToNull:protected] => Array
        (
            [0] => error_code
            [1] => message
        )
    [container:protected] => Array
        (
            [error_code] => 
            [message] => 
        ))
```
is this normal? because i can see my post request on the xendit dashboard log api page.

**Comment by adityarx** [comment]
Hi @NaMLiM, sorry about that. Would you mind giving us a reference id for the Payment Request you created? It would help us debug. Apologies for the inconvenience and thanks for your patience 🙏

**Comment by NaMLiM** [comment]
hello @adityarx, thanks for the response... this is my reference id INV1021301NS

**Comment by NaMLiM** [comment]
after looking into createPaymentRequest function i discovered that the function expected to see 200 status code but xendit send 201 status code. is this might be the problem?

**Comment by adityarx** [comment]
Yeap you're right @NaMLiM, we're fixing this on our end at the moment. Apologies on the issue~

**Comment by adityarx** [comment]
@NaMLiM our engineering team has just fixed this, could you upgrade to v3.1.0?

**Comment by NaMLiM** [comment]
@adityarx thank u it work now except for over the counter payment.
`
unsupported channel: merchant 'Anam' has not yet activated channel 'ID::ALFAMART'
`

i am in development mode and haven't activated my account. is this normal behaviour?

**Comment by adityarx** [comment]
Ah great to hear its now working @NaMLiM.

Unfortunately for Over-The-Counter Payments in Test mode, we require manual activation. Usually our customer support would be able to help you for this, but for now I've put in the request for you. You should have this channel activated later today.

Since the original issue is resolved, I will close the thread. If you need activation related help, I would suggest visiting this [link](https://help.xendit.co/hc/en-us/articles/4413769239833-Contact-Support) to reach out to our CS 🙏
