### ISSUE TITLE
API key is not authorized

### ISSUE THREAD

**Issue by msquareM** [xendit/xendit-php#82]
Hi,
 this is mani when i get balance from test mode show below error
"Xendit\Exceptions\ApiException
API key is not authorized for this API service"

my code look like below
Xendit::setApiKey('set_my secret_key');
$getBalance = \Xendit\Balance::getBalance('CASH');
dd($getBalance);

i am using laravel

**Comment by msquareM** [comment]
hi @kevindavee 

Thanks for your response. i am new to Xendit so what is MONEY_OUT permission ?.  where i found from dashboard

**Comment by stanleynguyen** [comment]
@msquareM you have to choose "READ" on money out while creating your API key to GET /balance
<img width="574" alt="Screenshot 2020-05-26 at 5 06 58 PM" src="https://user-images.githubusercontent.com/12974927/82882255-68692c80-9f73-11ea-9512-49fe639428c9.png">

**Comment by kevindavee** [comment]
Yes, so in order to use Xendit API, you need to:
1. Register for a [Xendit account](https://dashboard.xendit.co/register/1)
2. Create API key in the [Developer settings](https://dashboard.xendit.co/settings/developers#api-keys) with MONEY_OUT permission.

Thank you @stanleynguyen for providing the UI screenshot.

For further reading about API authentication, you may refer to this section in our [API reference](https://xendit.github.io/apireference/#authentication)

**Comment by msquareM** [comment]
Hi @stanleynguyen  @kevindavee 
    Thankyou  guys now its working fine
